"""The doctor points at the generator, and spots a driver that has gone stale.

A consumer hand-wrote a client instead of generating one, and reported
afterwards that EVERY mistake they made was in the half they wrote by hand.
Asked whether the SDK docstrings should advertise the scaffold, they argued
no, and the reasoning is why this lives here instead:

    "I did not skip the docstring.  I read it and believed it.  A pointer
     next to a wrong statement is never followed, because you only look for
     a second source when the first admits uncertainty."

A check EXECUTES.  It cannot go stale the way a cross-reference can — if an
archetype disappears this fails loudly instead of a sentence sitting there —
it fires at PREFLIGHT when the advice is still actionable, and it is in the
one tool people already run when something is wrong.

WARN, never FAIL: hand-writing a client is legitimate, and the doctor's exit
code gates CI.  A suggestion has no business failing a build.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from jaato_sdk.doctor import FAIL, PASS, WARN, check_driver

MARKER = "Generated by `jaato-scaffold new client --workspace .`"


def _driver(tmp_path: Path, name: str, body: str = "") -> Path:
    p = tmp_path / name
    p.write_text(f'"""A driver.\n\n{MARKER}\n"""\n{body}\n', encoding="utf-8")
    return p


def test_an_empty_workspace_is_told_where_the_recipe_is(tmp_path):
    (c,) = check_driver(str(tmp_path))

    assert c.status == WARN
    assert "jaato-scaffold new client" in c.detail
    assert "sweep" in c.detail, (
        "the other archetypes are not named, so a reader learns only that "
        "one exists"
    )


def test_it_warns_rather_than_fails(tmp_path):
    """The doctor's exit code gates CI.

    Hand-writing a client is a legitimate choice; a suggestion that fails a
    build teaches people to stop running the doctor, which costs more than
    the suggestion is worth.
    """
    (c,) = check_driver(str(tmp_path))

    assert c.status == WARN
    assert c.status != FAIL


def test_a_current_driver_passes(tmp_path):
    _driver(tmp_path, "run_client.py",
            "try:\n    sid = 1\nexcept Exception:\n    pass\n")

    (c,) = check_driver(str(tmp_path))

    assert c.status == PASS
    assert "run_client.py" in c.detail


def test_a_driver_written_against_the_old_contract_is_flagged(tmp_path):
    """The valuable half: not "you have no driver" but "yours has drifted".

    ``create_session`` returned ``Optional[str]`` until SDK 0.16; every
    template shipped ``if not sid:`` and two printed a guessed cause.  A
    driver generated before that still carries a dead branch and no handler
    for the exception that now occurs.
    """
    _driver(tmp_path, "run_client.py", "sid = 1\nif not sid:\n    pass\n")

    (c,) = check_driver(str(tmp_path))

    assert c.status == WARN
    assert "OLDER SDK contract" in c.detail
    assert "run_client.py" in c.detail
    assert "RAISES" in c.detail, (
        "the warning does not say what changed, so the reader cannot act "
        "on it without going to look"
    )


def test_a_guessed_cause_is_flagged_too(tmp_path):
    _driver(tmp_path, "d.py", 'print("check provider auth")\n')

    (c,) = check_driver(str(tmp_path))

    assert c.status == WARN
    assert "guessed cause" in c.detail


def test_a_stale_pattern_in_a_COMMENT_is_not_flagged(tmp_path):
    """A driver warning readers about the old pattern must not be flagged
    for mentioning it.

    This repo has sprung that trap four times — a guard failing on its own
    explanation.
    """
    _driver(tmp_path, "d.py", "# do not write: if not sid\nsid = 1\n")

    (c,) = check_driver(str(tmp_path))

    assert c.status == PASS


def test_a_file_without_the_marker_is_not_a_driver(tmp_path):
    """Only SCAFFOLDED files are judged.

    Someone's own module containing ``if not sid`` is none of the doctor's
    business, and flagging it would train people to ignore the check.
    """
    (tmp_path / "mine.py").write_text("sid = 0\nif not sid:\n    pass\n",
                                      encoding="utf-8")

    (c,) = check_driver(str(tmp_path))

    assert c.status == WARN
    assert "no scaffolded driver" in c.detail


@pytest.mark.parametrize("skipped", [".venv", "node_modules", "__pycache__"])
def test_vendored_trees_are_skipped(tmp_path, skipped):
    """A vendored copy of somebody else's driver is not this workspace's."""
    d = tmp_path / skipped
    d.mkdir()
    _driver(d, "run_client.py")

    (c,) = check_driver(str(tmp_path))

    assert c.status == WARN, (
        f"a driver inside {skipped}/ was counted as this workspace's"
    )


def test_a_missing_workspace_does_not_explode(tmp_path):
    (c,) = check_driver(str(tmp_path / "nope"))

    assert c.status == WARN
    assert "not a directory" in c.detail


def test_the_marker_matches_what_the_templates_actually_emit():
    """Checked against the TEMPLATES, not against a copy of the marker.

    The whole check hinges on this string.  If the generator's provenance
    line is reworded, this check silently reports "no scaffolded driver" for
    every workspace that has one — a false negative that looks like a clean
    result.
    """
    try:
        from shared.scaffold._client_templates import TEMPLATES
    except ImportError:                      # pragma: no cover
        pytest.skip("jaato-server not importable in this environment")

    from jaato_sdk.doctor import _SCAFFOLD_MARKER

    for name, (_, tmpl, _) in TEMPLATES.items():
        rendered = tmpl.replace("__PROVENANCE__", "jaato-scaffold new " + name)
        assert _SCAFFOLD_MARKER in rendered, (
            f"the {name} template no longer carries the provenance marker the "
            f"doctor looks for ({_SCAFFOLD_MARKER!r}); every scaffolded "
            "workspace would report as having no driver"
        )
