"""§2.6 / §8.2 acceptance gate — the 7:3 regression test.

Two clients in two different workspaces opt into AppArmor against a
single daemon.  Both must succeed end-to-end without a daemon bounce
between them, and a cli call from session-B must NOT be able to read
session-A's workspace files (kernel-enforced via the per-session
runner's AppArmor profile).

This test is the load-bearing acceptance gate for Phase 2.  Per
operator direction (plan §6.8), it runs on a user-hosted server with
CAP_MAC_ADMIN + CAP_SYSLOG; CI without those caps skips cleanly via
the ``apparmor`` mark + ``apparmor_available()`` skipif.

The test is structured as a scaffold:
- Helpers + fixture for spawning + tearing down a daemon subprocess.
- Profile-fixture writer producing the YAML profile shape from plan §4.
- The actual driving logic uses the ``IPCClient`` from jaato-sdk.

Phase 2 ships this test with a skipif that auto-skips on hosts
without AppArmor, so it's safe to commit.  The user-hosted runner
will exercise it for real.
"""

from __future__ import annotations

import asyncio
import os
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

import pytest

from ._apparmor_helpers import (
    SKIP_REASON_NO_APPARMOR,
    apparmor_available,
    dmesg_available,
)


pytestmark = [
    pytest.mark.apparmor,
    pytest.mark.skipif(not apparmor_available(), reason=SKIP_REASON_NO_APPARMOR),
]


# ----------------------------------------------------------------------
# Profile fixture (plan §4 review-edit B: YAML shape)
# ----------------------------------------------------------------------


CLI_TEST_PROFILE_YAML = """\
# Auto-generated by tests/integration/test_phase2_multitenant_apparmor.py
# Phase 2 acceptance-test profile — exercises the runner-side cli plugin
# via the daemon-side stub.  Permission policy is defaultPolicy=allow
# so the test runs autonomously without permission prompts.
name: cli_test
provider: anthropic
model: claude-sonnet-4-6
plugins:
  - signal_completion(preload)
  - cli
gc:
  type: budget
  threshold_percent: 80.0
plugin_configs:
  permission:
    policy:
      defaultPolicy: allow
      blacklist:
        tools: []
"""


def _provision_workspace(workspace: Path) -> None:
    """Create the minimum on-disk shape an apparmor-enabled session needs."""
    profiles_dir = workspace / ".jaato" / "profiles"
    profiles_dir.mkdir(parents=True, exist_ok=True)
    (profiles_dir / "cli_test.yaml").write_text(CLI_TEST_PROFILE_YAML)
    sandbox = workspace / "sandbox"
    sandbox.mkdir(exist_ok=True)


# ----------------------------------------------------------------------
# Daemon fixture
# ----------------------------------------------------------------------


#: The daemon's entry point.  The package is ``jaato_server`` (see
#: CLAUDE.md, "Running the Server"); this test used to launch
#: ``python -m server``, a module that no longer exists, so on every host
#: where the file does not skip it failed before any session existed
#: (#1462).  ``test_integration_tests_launch_real_modules_1462.py`` checks
#: every ``-m <module>`` launch under ``jaato-server/tests/`` resolves.
DAEMON_MODULE = "jaato_server"

#: How long the daemon may take to put its IPC socket on disk.  It spawns
#: the pre-warm template before it listens, so 5 s was tight on a loaded
#: host; a slow start is not what this gate measures.
DAEMON_READY_SECONDS = 30


def _start_daemon(socket_path: Path, log_path: Path) -> subprocess.Popen:
    """Launch ``python -m jaato_server --ipc-socket <path>`` in the foreground.

    We deliberately do NOT use ``--daemon`` (double-fork) because we want
    to own the subprocess lifecycle from this fixture.  Instead the
    daemon runs in the foreground; we kill it directly at teardown.
    IPC only: no ``--web-socket``, so no WS bearer token is involved.
    """
    env = os.environ.copy()
    proc = subprocess.Popen(
        [
            sys.executable,
            "-m",
            DAEMON_MODULE,
            "--ipc-socket",
            str(socket_path),
        ],
        stdout=open(log_path, "ab"),
        stderr=subprocess.STDOUT,
        env=env,
    )
    # Wait for the socket to become ready.
    deadline = time.monotonic() + DAEMON_READY_SECONDS
    while time.monotonic() < deadline:
        if socket_path.exists():
            try:
                with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as s:
                    s.settimeout(0.5)
                    s.connect(str(socket_path))
                return proc
            except OSError:
                pass
        if proc.poll() is not None:
            raise AssertionError(
                f"daemon exited early with rc={proc.returncode}; "
                f"see {log_path}"
            )
        time.sleep(0.1)
    proc.terminate()
    raise AssertionError(
        f"daemon socket {socket_path} did not appear in "
        f"{DAEMON_READY_SECONDS}s; see {log_path}"
    )


def _stop_daemon(proc: subprocess.Popen) -> None:
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=2)


# ----------------------------------------------------------------------
# The 7:3 regression test
# ----------------------------------------------------------------------


def test_two_workspaces_one_daemon_no_bounce(tmp_path: Path) -> None:
    """Two clients, two workspaces, one daemon — both succeed, cross-
    workspace cli reads are kernel-denied.

    This is the ${prompt}'s §2.6 IS THE GATE test.  Implemented
    against the IPCClient SDK so the wire path is identical to a real
    TUI session.

    The test is intentionally written so each step explains itself in
    a failure message — when this test fires red, the assertion
    explains exactly which step regressed.
    """
    asyncio.run(_drive_two_workspaces(tmp_path))


async def _drive_two_workspaces(tmp_path: Path) -> None:
    """The body of the gate above, as a coroutine.

    Separated because ``IPCClient`` is an ASYNC client and this test
    drove it as a synchronous one -- ``connect(workspace=..., apparmor=
    ...)``, ``session_new``, ``wait_for_idle`` and ``get_history`` are
    all spellings that no longer exist anywhere in the SDK.  The first
    of them to be reached raised, so this gate had rotted through and
    through while reading as green (#736).

    THE REASON IT ROTTED UNSEEN IS THE ISSUE'S OWN THESIS, one level in.
    ``jaato-server/tests/`` was measured as green-and-wire-ready on two
    separate hosts, and both were hosts WITHOUT AppArmor -- where the
    module-level ``skipif`` above makes this file skip, and a skip is
    indistinguishable from a pass in a summary line.  CI has AppArmor,
    so the first commit-triggered run that actually reached this body
    found it broken.  "Green" measured in the wrong environment is not
    green, and this gate is the proof.

    Driven through the same idiom the live-conformance suite uses
    (``jaato_sdk/conformance/test_invariants.py``), which is the one
    daemon-driving pattern in this tree a commit-triggered workflow
    exercises -- so it cannot drift again without that suite going red
    too.
    """
    from jaato_sdk import IPCClient
    from jaato_sdk.events import ClientType

    ws_a = tmp_path / "ws_a"
    ws_b = tmp_path / "ws_b"
    ws_a.mkdir()
    ws_b.mkdir()
    _provision_workspace(ws_a)
    _provision_workspace(ws_b)

    sock = tmp_path / "jaato.sock"
    daemon_log = tmp_path / "daemon.log"
    daemon = _start_daemon(sock, daemon_log)

    client_a = client_b = None
    try:
        # ----- Client A: workspace_a session -----
        client_a = await _connect(
            IPCClient, ClientType, sock, ws_a,
        )
        sid_a = await client_a.create_session(profile="cli_test")
        assert sid_a, "session.new for client A returned no session_id"
        # #1253: the session's FIRST runner wears its profile from the
        # start, read from the kernel before any turn has run -- not the
        # runner a later turn or a revive gets.
        _assert_runner_wears_its_profile(
            await _runner_identity(client_a, sid_a))

        # Write a workspace-A file via cli — exercises the runner.
        await _drive_turn(
            client_a,
            f"create file via cli: echo hi-from-A > {ws_a}/sandbox/x",
        )
        assert (ws_a / "sandbox" / "x").exists(), (
            "session A's cli call did not create sandbox/x; the runner "
            "may have spawned but the cli RPC stub may not be wired"
        )

        # ----- Client B: the 7:3 regression case -----
        # NO daemon bounce between A and B.  This is the load-bearing
        # assertion: pre-Phase-2, the daemon's apparmor profile was
        # pinned to A's workspace and B's session.new failed at the
        # IPC handshake.
        client_b = await _connect(
            IPCClient, ClientType, sock, ws_b,
        )
        sid_b = await client_b.create_session(profile="cli_test")
        assert sid_b, (
            "session.new for client B returned no session_id — "
            "this is the 7:3 regression case (cross-workspace IPC "
            "handshake failed)"
        )

        await _drive_turn(
            client_b,
            f"create file via cli: echo hi-from-B > {ws_b}/sandbox/y",
        )
        assert (ws_b / "sandbox" / "y").exists()

        # ----- Which profile each runner wears -----
        # Profiles are named after the BOUNDARY (workspace + rendered
        # body), not the session (#1033 / #1037): ``jaato-ws-<slug>-
        # <digest>``.  Read the name the daemon recorded for each runner
        # (#812's runner identity, on the ``session.list`` rows) rather
        # than reconstructing it.
        profile_a = await _runner_profile(client_a, sid_a)
        profile_b = await _runner_profile(client_b, sid_b)
        assert profile_a and profile_b and profile_a != profile_b, (
            f"two workspaces must be two AppArmor boundaries; got "
            f"A={profile_a!r} B={profile_b!r}"
        )

        # ----- Cross-workspace read MUST be kernel-denied -----
        # Wrapped in ``sh -c`` on purpose: a bare ``cat <path>`` outside
        # the workspace is refused by cli's own path check before
        # anything runs, which proves the string layer and leaves the
        # kernel untouched.  The analyzer does not descend into the
        # quoted argument of ``sh -c``, so this read reaches the
        # ``//child`` profile and is the kernel's to deny.
        await _drive_turn(
            client_b,
            f"run exactly this with the cli tool, unchanged: "
            f"sh -c 'cat {ws_a}/sandbox/x'",
        )
        # The cli result on B should report Permission denied.  There is
        # no structured-result accessor on the SDK, so pull the session's
        # history and walk it for the last cli payload.
        history = await _history(client_b)
        _assert_cross_read_denied(_last_cli_result(history))
        _assert_kernel_denial(profile_b, ws_a / "sandbox" / "x")
    except BaseException:
        # The daemon's stdout/stderr is the only account of WHY a step
        # failed, and until now this test wrote it to ``tmp_path`` and
        # never read it -- so the first CI run to reach this body
        # reported ``SessionNotConfirmed: session.new was sent but not
        # answered within 60.0s`` and nothing about the refusal the
        # daemon had already logged.  That is the #882 shape seen from
        # the client side: a refused ``session.new`` is logged and never
        # answered, so the caller learns only that it waited.
        #
        # Printed rather than raised-with: pytest captures stdout and
        # shows it on failure, and a teardown that itself raises must not
        # be able to replace the original exception.
        _print_daemon_log(daemon_log)
        raise
    finally:
        for client in (client_a, client_b):
            if client is not None:
                try:
                    await client.disconnect()
                except Exception:       # noqa: BLE001 - teardown only
                    pass
        _stop_daemon(daemon)


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def _print_daemon_log(log_path: Path, tail_lines: int = 120) -> None:
    """Emit the daemon's own account of a failed step.

    This test spawns the daemon itself and sends its stdout+stderr to
    ``tmp_path/daemon.log``.  That file was written and never read: on
    the first commit-triggered run that actually reached this body, the
    failure surfaced as a bare 60 s ``SessionNotConfirmed`` while the
    reason sat on disk, and ``tmp_path`` was then cleaned away.

    Tail rather than whole: bootstrap chatter dominates the head, and
    the answer to "why did this step fail" is always at the end.
    Best-effort by construction -- a diagnostic that can itself raise
    would replace the exception it exists to explain.
    """
    try:
        text = log_path.read_text(errors="replace")
    except OSError as exc:              # noqa: BLE001 - diagnostic only
        print(f"\n--- daemon log at {log_path} unreadable: {exc} ---")
        return

    lines = text.splitlines()
    shown = lines[-tail_lines:]
    elided = len(lines) - len(shown)
    print(f"\n--- daemon log ({log_path}), last {len(shown)} of "
          f"{len(lines)} lines ---")
    if elided > 0:
        print(f"    [{elided} earlier lines elided]")
    for line in shown:
        print(f"    {line}")
    print("--- end daemon log ---\n")



def _assert_cross_read_denied(last_result: Optional[dict]) -> None:
    """The cross-workspace read failed, and it was not cli's string
    check that stopped it (that would leave the kernel unexercised)."""
    assert last_result is not None, (
        "expected a cli tool result in B's history after the "
        "cross-workspace read attempt"
    )
    assert "cli containment" not in (last_result.get("error") or ""), (
        "cli's string-level path check refused the read before it "
        "ran, so the kernel boundary was never exercised: "
        f"{last_result!r}"
    )
    # Either the cli returns a non-zero exit (cat: ENOENT
    # because apparmor masks the path as not-found) OR the
    # result.error mentions Permission denied.  Both are
    # legitimate apparmor-enforced outcomes.
    assert (
        "Permission denied" in (last_result.get("stderr") or "")
        or "Permission denied" in (last_result.get("error") or "")
        or last_result.get("returncode", 0) != 0
    ), (
        f"expected cross-workspace cat to fail but got {last_result!r}"
    )


def _assert_kernel_denial(profile: str, path: Path) -> None:
    """dmesg carries a DENIED line for *profile* on *path*.

    ONE audit line must carry all three facts: a denial, the profile
    (``//child`` included, hence the open quote), and the file.
    ``tmp_path`` is unique per run, so the name alone scopes the match
    to this test.  The old check looked for ``profile="jaato-ws-<session
    id>`` -- a name no profile has carried since #1033 -- and for
    "DENIED" anywhere in the ring buffer.
    """
    if not dmesg_available():
        print(
            "dmesg unavailable — skipping kernel-audit assertion. "
            "Userspace assertions still cover the deny."
        )
        return
    dmesg = subprocess.check_output(["dmesg", "-T"]).decode(errors="replace")
    target = f'name="{path}"'
    denials = [
        line for line in dmesg.splitlines()
        if 'apparmor="DENIED"' in line
        and f'profile="{profile}' in line
        and target in line
    ]
    assert denials, (
        f"expected a DENIED apparmor audit line for profile {profile} "
        f"on {path}; none found"
    )


async def _connect(ipc_client_cls, client_type_enum, sock: Path, ws: Path):
    """Connect one AppArmor-confined client to the shared daemon.

    ``workspace_path`` and ``apparmor`` are CONSTRUCTOR arguments; this
    test used to pass them to ``connect()``, which takes only a timeout.
    ``client_type`` is required (keyword-only) and is what the CI run
    tripped over first.  ``auto_start=False`` because the daemon in this
    test is spawned by hand and shared by both clients — the whole point
    of the gate is that there is NO bounce between A and B.
    """
    client = ipc_client_cls(
        socket_path=str(sock),
        client_type=client_type_enum.API,
        workspace_path=str(ws),
        apparmor=True,
        auto_start=False,
    )
    assert await client.connect(timeout=60), (
        f"could not connect to the test daemon at {sock} for workspace {ws}"
    )
    return client


async def _drive_turn(client, prompt: str, timeout: float = 60.0) -> None:
    """Send one prompt and wait for the turn to complete.

    Replaces the ``send_message`` + ``wait_for_idle`` pair this test used
    to call; neither exists on the async client.  The collector is armed
    BEFORE the send, as in the conformance suite, or a fast turn can
    complete before anything is listening and the wait hangs to its
    timeout.
    """
    from jaato_sdk.events import TurnCompletedEvent

    async def collect():
        async for ev in client.events():
            if isinstance(ev, TurnCompletedEvent):
                return

    task = asyncio.create_task(collect())
    await asyncio.sleep(0.2)
    await client.send_message(prompt)
    try:
        await asyncio.wait_for(task, timeout=timeout)
    except asyncio.TimeoutError:
        task.cancel()
        raise AssertionError(
            f"no TurnCompletedEvent within {timeout}s for prompt {prompt!r}"
        )


async def _runner_profile(client, session_id: str,
                          timeout: float = 30.0) -> str:
    """The AppArmor profile the daemon recorded for a session's runner.

    ``session.list`` rows carry ``runner`` -- the #812 runner identity,
    whose ``apparmor_profile`` is the profile the runner was spawned
    into.  An empty value means the session is NOT confined, which this
    gate treats as a failure: everything after it would be measuring an
    unconfined runner.
    """
    identity = await _runner_identity(client, session_id, timeout)
    profile = identity.get("apparmor_profile") or ""
    assert profile.startswith("jaato-ws-"), (
        f"session {session_id}'s runner is not AppArmor-confined "
        f"(runner identity: {identity!r})"
    )
    return profile


def _assert_runner_wears_its_profile(identity: dict) -> None:
    """Every thread of the runner wears its recorded profile, enforced (#1253).

    #1100 / #1253: a session's first runner (a pool slot) spawned before
    the profile was provisioned and served the session unconfined while
    the daemon recorded ``apparmor``.  The daemon now refuses a session
    whose runner does not report the profile; this reads the KERNEL's
    answer for the process the daemon named, so a run on an enforcing
    host checks the fix rather than the daemon's account of it.
    """
    pid = identity.get("runner_pid")
    profile = identity.get("apparmor_profile") or ""
    assert pid and profile.startswith("jaato-ws-"), (
        f"no confined runner recorded: {identity!r}"
    )
    task_dir = Path(f"/proc/{pid}/task")
    labels = {}
    for task in sorted(task_dir.iterdir()):
        raw = (task / "attr" / "current").read_text(errors="replace")
        labels[task.name] = raw.replace("\x00", "").strip()
    # Through the one label parser (#1014 / #1509): a stack with
    # ``unconfined`` is its profile, the mode must be enforce.
    from jaato_server.shared.apparmor_label import parse_label
    wrong = {
        tid: label for tid, label in labels.items()
        if parse_label(label).profile != profile
        or not parse_label(label).enforced
    }
    assert not wrong, (
        f"runner pid={pid} should wear {profile!r} (enforce) on every "
        f"thread; these do not: {wrong!r}"
    )


async def _runner_identity(client, session_id: str,
                           timeout: float = 30.0) -> dict:
    """The #812 runner identity the daemon recorded for *session_id*."""
    from jaato_sdk.events import SessionListEvent

    async def collect():
        async for ev in client.events():
            if isinstance(ev, SessionListEvent):
                return list(ev.sessions)
        return []

    task = asyncio.create_task(collect())
    await asyncio.sleep(0.2)
    await client.list_sessions()
    try:
        rows = await asyncio.wait_for(task, timeout=timeout)
    except asyncio.TimeoutError:
        task.cancel()
        raise AssertionError(f"no SessionListEvent within {timeout}s")
    row = next((r for r in rows if r.get("id") == session_id), None)
    assert row is not None, f"session {session_id} not in session.list"
    return dict(row.get("runner") or {})


async def _history(client, timeout: float = 30.0) -> list:
    """Fetch the session's history.

    ``get_history()`` was a synchronous accessor and is gone: history is
    REQUESTED and arrives as a ``HistoryEvent`` on the event stream.
    """
    from jaato_sdk.events import HistoryEvent

    async def collect():
        async for ev in client.events():
            if isinstance(ev, HistoryEvent):
                return list(ev.history)
        return []

    task = asyncio.create_task(collect())
    await asyncio.sleep(0.2)
    await client.request_history()
    try:
        return await asyncio.wait_for(task, timeout=timeout)
    except asyncio.TimeoutError:
        task.cancel()
        raise AssertionError(f"no HistoryEvent within {timeout}s")


def _last_cli_result(history) -> Optional[dict]:
    """Walk a session's history backwards looking for the last cli
    tool result.  Returns the result dict (the structured payload the
    daemon-side stub forwarded) or ``None`` if nothing matched.

    ``HistoryEvent.history`` carries SERIALIZED ``Message`` dicts --
    ``{role, parts: [{type: 'function_response', call_id, name, result},
    ...]}`` -- so the payload sits one level down, inside a part, and a
    walk over the top level alone finds nothing.  The flat shapes are
    still accepted first: this helper predates the async history path
    and a tolerant match costs nothing.
    """
    if not history:
        return None
    items = list(history) if not isinstance(history, list) else history

    def _payload(candidate) -> Optional[dict]:
        if not isinstance(candidate, dict):
            return None
        if "stdout" in candidate or "returncode" in candidate:
            return candidate
        inner = candidate.get("result") or candidate.get("tool_result")
        if isinstance(inner, dict) and (
            "stdout" in inner or "returncode" in inner
        ):
            return inner
        return None

    for item in reversed(items):
        hit = _payload(item)
        if hit is not None:
            return hit
        # Descend into a serialized Message's parts.
        if isinstance(item, dict):
            for part in reversed(item.get("parts") or []):
                hit = _payload(part)
                if hit is not None:
                    return hit
    return None
