"""§2.6 / §8.2 acceptance gate — the 7:3 regression test.

Two clients in two different workspaces opt into AppArmor against a
single daemon.  Both must succeed end-to-end without a daemon bounce
between them, and a cli call from session-B must NOT be able to read
session-A's workspace files (kernel-enforced via the per-session
runner's AppArmor profile).

This test is the load-bearing acceptance gate for Phase 2.  Per
operator direction (plan §6.8), it runs on a user-hosted server with
CAP_MAC_ADMIN + CAP_SYSLOG; CI without those caps skips cleanly via
the ``apparmor`` mark + ``apparmor_available()`` skipif.

The test is structured as a scaffold:
- Helpers + fixture for spawning + tearing down a daemon subprocess.
- Profile-fixture writer producing the YAML profile shape from plan §4.
- The actual driving logic uses the ``IPCClient`` from jaato-sdk.

Phase 2 ships this test with a skipif that auto-skips on hosts
without AppArmor, so it's safe to commit.  The user-hosted runner
will exercise it for real.
"""

from __future__ import annotations

import asyncio
import os
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

import pytest

from ._apparmor_helpers import (
    SKIP_REASON_NO_APPARMOR,
    apparmor_available,
    dmesg_available,
)


pytestmark = [
    pytest.mark.apparmor,
    pytest.mark.skipif(not apparmor_available(), reason=SKIP_REASON_NO_APPARMOR),
]


# ----------------------------------------------------------------------
# Profile fixture (plan §4 review-edit B: YAML shape)
# ----------------------------------------------------------------------


CLI_TEST_PROFILE_YAML = """\
# Auto-generated by tests/integration/test_phase2_multitenant_apparmor.py
# Phase 2 acceptance-test profile — exercises the runner-side cli plugin
# via the daemon-side stub.  Permission policy is defaultPolicy=allow
# so the test runs autonomously without permission prompts.
name: cli_test
provider: anthropic
model: claude-sonnet-4-6
plugins:
  - signal_completion(preload)
  - cli
gc:
  type: budget
  threshold_percent: 80.0
plugin_configs:
  permission:
    policy:
      defaultPolicy: allow
      blacklist:
        tools: []
"""


def _provision_workspace(workspace: Path) -> None:
    """Create the minimum on-disk shape an apparmor-enabled session needs."""
    profiles_dir = workspace / ".jaato" / "profiles"
    profiles_dir.mkdir(parents=True, exist_ok=True)
    (profiles_dir / "cli_test.yaml").write_text(CLI_TEST_PROFILE_YAML)
    sandbox = workspace / "sandbox"
    sandbox.mkdir(exist_ok=True)


# ----------------------------------------------------------------------
# Daemon fixture
# ----------------------------------------------------------------------


def _start_daemon(socket_path: Path, log_path: Path) -> subprocess.Popen:
    """Launch ``python -m server --ipc-socket <path> --daemon=False``.

    We deliberately do NOT use --daemon (double-fork) because we want
    to own the subprocess lifecycle from this fixture.  Instead the
    daemon runs in the foreground; we kill it directly at teardown.
    """
    env = os.environ.copy()
    proc = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "server",
            "--ipc-socket",
            str(socket_path),
        ],
        stdout=open(log_path, "ab"),
        stderr=subprocess.STDOUT,
        env=env,
    )
    # Wait for the socket to become ready (≤5 s).
    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        if socket_path.exists():
            try:
                with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as s:
                    s.settimeout(0.5)
                    s.connect(str(socket_path))
                return proc
            except OSError:
                pass
        if proc.poll() is not None:
            raise AssertionError(
                f"daemon exited early with rc={proc.returncode}; "
                f"see {log_path}"
            )
        time.sleep(0.1)
    proc.terminate()
    raise AssertionError(f"daemon socket {socket_path} did not appear in 5s")


def _stop_daemon(proc: subprocess.Popen) -> None:
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=2)


# ----------------------------------------------------------------------
# The 7:3 regression test
# ----------------------------------------------------------------------


def test_two_workspaces_one_daemon_no_bounce(tmp_path: Path) -> None:
    """Two clients, two workspaces, one daemon — both succeed, cross-
    workspace cli reads are kernel-denied.

    This is the ${prompt}'s §2.6 IS THE GATE test.  Implemented
    against the IPCClient SDK so the wire path is identical to a real
    TUI session.

    The test is intentionally written so each step explains itself in
    a failure message — when this test fires red, the assertion
    explains exactly which step regressed.
    """
    from jaato_sdk.client import IPCClient

    ws_a = tmp_path / "ws_a"
    ws_b = tmp_path / "ws_b"
    ws_a.mkdir()
    ws_b.mkdir()
    _provision_workspace(ws_a)
    _provision_workspace(ws_b)

    sock = tmp_path / "jaato.sock"
    daemon_log = tmp_path / "daemon.log"
    daemon = _start_daemon(sock, daemon_log)

    # Per-test snapshot of the dmesg cursor so we can assert ONLY on
    # apparmor entries produced during this run.
    dmesg_baseline_t = time.time()

    try:
        # ----- Client A: workspace_a session -----
        client_a = IPCClient(socket_path=str(sock))
        client_a.connect(workspace=str(ws_a), apparmor=True)
        sid_a = client_a.session_new(profile="cli_test")
        assert sid_a, "session.new for client A returned no session_id"

        # Write a workspace-A file via cli — exercises the runner.
        client_a.send_message(
            f"create file via cli: echo hi-from-A > {ws_a}/sandbox/x"
        )
        client_a.wait_for_idle(timeout=30)
        assert (ws_a / "sandbox" / "x").exists(), (
            "session A's cli call did not create sandbox/x; the runner "
            "may have spawned but the cli RPC stub may not be wired"
        )

        # ----- Client B: the 7:3 regression case -----
        # NO daemon bounce between A and B.  This is the load-bearing
        # assertion: pre-Phase-2, the daemon's apparmor profile was
        # pinned to A's workspace and B's session.new failed at the
        # IPC handshake.
        client_b = IPCClient(socket_path=str(sock))
        client_b.connect(workspace=str(ws_b), apparmor=True)
        sid_b = client_b.session_new(profile="cli_test")
        assert sid_b, (
            "session.new for client B returned no session_id — "
            "this is the 7:3 regression case (cross-workspace IPC "
            "handshake failed)"
        )

        client_b.send_message(
            f"create file via cli: echo hi-from-B > {ws_b}/sandbox/y"
        )
        client_b.wait_for_idle(timeout=30)
        assert (ws_b / "sandbox" / "y").exists()

        # ----- Cross-workspace read MUST be kernel-denied -----
        client_b.send_message(
            f"read file: cat {ws_a}/sandbox/x"
        )
        client_b.wait_for_idle(timeout=30)
        # The cli result on B should report Permission denied.  We
        # don't have a structured-result accessor on the SDK level,
        # so fall back to reading the daemon log for the cli result
        # OR pulling the last tool result from the client's history.
        history = client_b.get_history()
        last_result = _last_cli_result(history)
        assert last_result is not None, (
            "expected a cli tool result in B's history after the "
            "cross-workspace read attempt"
        )
        # Either the cli returns a non-zero exit (cat: ENOENT
        # because apparmor masks the path as not-found) OR the
        # result.error mentions Permission denied.  Both are
        # legitimate apparmor-enforced outcomes.
        assert (
            "Permission denied" in (last_result.get("stderr") or "")
            or "Permission denied" in (last_result.get("error") or "")
            or last_result.get("returncode", 0) != 0
        ), (
            f"expected cross-workspace cat to fail but got {last_result!r}"
        )

        # ----- Kernel-side audit confirmation -----
        if dmesg_available():
            dmesg = subprocess.check_output(["dmesg", "-T"]).decode()
            # The runner's profile name should appear in a DENIED
            # audit line corresponding to the cross-workspace read.
            expected_profile_marker = f'profile="jaato-ws-{sid_b}'
            assert expected_profile_marker in dmesg, (
                f"expected dmesg to carry an apparmor entry for "
                f"profile jaato-ws-{sid_b} but no match found"
            )
            assert "DENIED" in dmesg, (
                "expected at least one DENIED apparmor audit entry"
            )
        else:
            print(
                "dmesg unavailable — skipping kernel-audit assertion. "
                "Userspace assertions still cover the deny."
            )
    finally:
        _stop_daemon(daemon)


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def _last_cli_result(history) -> Optional[dict]:
    """Walk a session's history backwards looking for the last cli
    tool result.  Returns the result dict (the structured payload the
    daemon-side stub forwarded) or ``None`` if nothing matched.

    The exact accessor depends on the SDK's history shape; this
    helper is intentionally tolerant — it looks for any dict-like
    item that carries ``returncode`` / ``stdout`` / ``stderr`` keys.
    """
    if not history:
        return None
    items = list(history) if not isinstance(history, list) else history
    for item in reversed(items):
        # Try a few common shapes.
        if isinstance(item, dict):
            if "stdout" in item or "returncode" in item:
                return item
            payload = item.get("result") or item.get("tool_result")
            if isinstance(payload, dict) and (
                "stdout" in payload or "returncode" in payload
            ):
                return payload
    return None
