"""``jaato-scaffold explain`` without jaato-server: answered from a snapshot.

``explain`` renders the INSTALLED framework: the plugin registry, the provider
contracts, the event protocol, the profile schema.  Its renderers live in
jaato-server, so an application that installs only jaato-sdk had no
``explain`` at all unless a daemon was running to ask.  Almost every topic is
a deterministic function of the installed code, though, so jaato-server
renders them ahead of time and jaato-sdk ships the result:
:data:`SNAPSHOT_FILE`, generated by
:mod:`jaato_server.shared.scaffold.explain_snapshot`.

**What it holds.**  Every built-in topic ``render_topic`` answers without a
caller's argument: the overview, each ``simple`` topic, each ``filter`` topic
unfiltered, the bare form of each ``optional_named`` topic, and every name of
each ``named`` topic (``plugin cli``, ``event agent.output``, ...), with the
spellings each name is accepted under.  Each entry is the ``(data, text)``
pair the live renderer returned, so ``--json`` and text print exactly what a
jaato-server install would have printed.

**What it does not hold**, and therefore still needs jaato-server or a daemon:

- topics marked ``live_only`` on the server's topic table, whose answer
  describes the machine or the moment (``releases``, ``integrations``,
  ``runner-user``).  Their reasons travel in the snapshot (:func:`live_only`);
- topics that read the caller's workspace (``sets``, ``agents``,
  ``services``, ``profile <name>``, ``oversight <name>``, ``audit <name>``);
- a filtered ``env`` / ``events``;
- topics and sections contributed by other installed packages (premium's
  ``reactors``): the snapshot is generated from jaato-server alone, and an
  extension exists only where it is installed;
- the ``dependencies`` facet, which describes THIS environment.

**Provenance.**  Every answer names the jaato-server version it was rendered
from, as a daemon's answer names the daemon.  A reader cannot otherwise tell
the snapshot shipped with their jaato-sdk from the framework a daemon is
running.

Stdlib only; nothing here imports jaato_server.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

#: The checked-in snapshot.  Regenerated with
#: ``python -m jaato_server.shared.scaffold.explain_snapshot --write``.
SNAPSHOT_FILE = Path(__file__).with_name("explain_snapshot.json")

#: Bumped when the file's SHAPE changes, so a reader never half-parses a file
#: written for another shape.
SNAPSHOT_VERSION = 1

#: The key the overview (``explain`` with no topic) is stored under.
OVERVIEW_KEY = ""

_CACHE: Optional[Dict[str, Any]] = None


def entry_key(scope: Optional[str], name: Optional[str] = None) -> str:
    """The key a rendering is stored under: ``""``, ``"scope"``, ``"scope name"``."""
    if not scope:
        return OVERVIEW_KEY
    return f"{scope} {name}" if name else scope


def load() -> Optional[Dict[str, Any]]:
    """The parsed snapshot, or ``None`` when this install carries none.

    An unreadable file or one of another shape reads as absent: the caller
    then falls through to a daemon or the refusal, which name a fix, rather
    than printing half of an answer.
    """
    global _CACHE
    if _CACHE is None:
        try:
            data = json.loads(SNAPSHOT_FILE.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        if data.get("snapshot_version") != SNAPSHOT_VERSION:
            return None
        _CACHE = data
    return _CACHE


def resolve(scope: Optional[str], name: Optional[str]) -> Optional[str]:
    """The canonical key for *scope* / *name*, or ``None`` if not snapshotted.

    A named topic's argument goes through the spellings the generator
    recorded for it, so an alias finds the canonical rendering exactly as the
    live lookup would.  A spelling the live lookup would only have SUGGESTED
    (``did you mean``) is not recorded and resolves to nothing.
    """
    data = load()
    if data is None:
        return None
    topics = data["topics"]
    if name:
        canonical = data["aliases"].get(scope or "", {}).get(name)
        if canonical is None:
            return None
        key = entry_key(scope, canonical)
    else:
        key = entry_key(scope)
    return key if key in topics else None


def answer(scope: Optional[str], name: Optional[str]
           ) -> Optional[Tuple[Dict[str, Any], str]]:
    """``(data, text)`` for *scope* / *name*, or ``None`` when not snapshotted."""
    key = resolve(scope, name)
    if key is None:
        return None
    entry = load()["topics"][key]
    return entry["data"], entry["text"]


def server_version() -> str:
    """The jaato-server version the snapshot was rendered from."""
    data = load() or {}
    return data.get("jaato_server_version") or "unknown version"


def live_only() -> Dict[str, str]:
    """Topic -> why it is not in the snapshot, for the topics that say so."""
    data = load() or {}
    return dict(data.get("live_only", {}))


def topics() -> List[str]:
    """The topics with at least one snapshotted rendering, in table order."""
    data = load()
    if data is None:
        return []
    return list(data.get("scopes", []))


def attribution() -> str:
    """The line naming whose install a snapshot answer describes.

    Printed under every text answer, as :func:`remote.attribution` is under a
    daemon's.
    """
    return (f"[from the jaato-server {server_version()} snapshot shipped with "
            f"jaato-sdk — not a running daemon; --connect asks one]")


def miss_note(scope: Optional[str], name: Optional[str]) -> str:
    """Why the snapshot could not answer, for the refusal to print after it.

    Empty when there is no snapshot at all, so the refusal stays as it was.
    """
    data = load()
    if data is None:
        return ""
    reasons = live_only()
    if scope in reasons:
        return (f"(`explain {scope}` is not in the snapshot shipped with "
                f"jaato-sdk: it {reasons[scope]})")
    if scope in data.get("reads_workspace", []) and (
            name or scope not in topics()):
        return (f"(`explain {scope}{' ' + name if name else ''}` reads your "
                f"workspace, which the snapshot shipped with jaato-sdk cannot "
                f"do)")
    if scope in topics() and name:
        return (f"(the snapshot shipped with jaato-sdk has no `explain "
                f"{scope} {name}`: a name it does not list, a filter, or a "
                f"topic that reads your workspace)")
    return (f"(the snapshot shipped with jaato-sdk answers: "
            f"{', '.join(topics())})")
