"""Runnable SDK-client templates for ``jaato-scaffold new <archetype>``.

Each template bakes in the verified known-good recipe (the hard-won lessons
from the LORA-specialist transcript), so a generated client doesn't repeat the
hour of trial-and-error:

- ``IPCClient(client_type=ClientType.API)`` — **load-bearing**: the daemon
  keeps ``signal_completion`` for API clients (strips it for TERMINAL/WEB/CHAT
  roots), so headless completion works.
- ``connect(timeout=120.0)`` — a COLD daemon autostart takes ~30-60s; the SDK
  default (5s) is too low.
- ``env_file`` is always a real path — ``env_file=None`` crashes the IPC
  handshake with an opaque ``os.PathLike`` TypeError.
- completion via first-of ``{TURN_COMPLETED, SESSION_TERMINATED}`` then wait —
  a completion-gated session (its persona calls ``signal_completion``) emits
  ``SESSION_TERMINATED`` carrying the rich ``reason`` (``natural``/``error``;
  ``error_summary`` / ``error_type`` on error).  A PLAIN turn that just answers
  emits only ``TURN_COMPLETED`` and the session then goes IDLE — a headless
  session does NOT self-terminate after its prompt, so ``SESSION_TERMINATED``
  never fires on that happy path.  Waiting on ``SESSION_TERMINATED`` alone
  would block forever; subscribing to BOTH (mirrors the framework's own
  ``run_ephemeral`` terminal detection — jaato PR #316) fixes the plain-turn
  hang while still surfacing errors via ``SESSION_TERMINATED(reason="error")``.
  NOT ``set_event_callback`` (which does not exist — the phantom method that
  ate the peer's tracing).

Templates use ``__TOKEN__`` placeholders filled by ``str.replace`` so the
embedded Python (dict literals, async braces) needs no escaping.
"""

ENV_TEMPLATE = """\
# Generated by `jaato-scaffold new`. A real .env is REQUIRED — the IPC
# handshake crashes on env_file=None.  Fill the provider key (or use a
# pass:// URI in the profile's plugin_configs instead of a raw key here).
JAATO_PROVIDER=__PROVIDER__
MODEL_NAME=__MODEL__
# __KEY_ENV__=<your key>   # or store via the provider's auth command
"""


_COMMON_HEADER = '''#!/usr/bin/env python3
"""__TITLE__

Generated by `__PROVENANCE__`.
Preflight first:
  python -m jaato_sdk.doctor --workspace __WORKSPACE__ --env-file __ENV_FILE__
"""
import asyncio
__CLIENT_IMPORT__

ENV_FILE = "__ENV_FILE__"
WORKSPACE = "__WORKSPACE__"
MODEL = "__MODEL__"
PROVIDER = "__PROVIDER__"
__CONN_CONSTANTS__


__ON_STATUS_DEF__def _new_client():
    """Construct the API client with the known-good knobs."""
    return __NEW_CLIENT_CALL__
'''


CLIENT_TEMPLATE = _COMMON_HEADER + '''

async def main() -> int:
    client = _new_client()
    if not await client.connect(timeout=120.0):   # cold autostart ~30-60s
        print("could not connect/autostart the daemon — run the doctor")
        return 1

    done = asyncio.Event()
    outcome = {}

    def on_done(ev):
        # Wake on whichever terminal lands first.  A completion-gated session
        # (profile/persona calls signal_completion) emits SESSION_TERMINATED
        # with a rich reason/error.  A PLAIN turn that just answers emits only
        # TURN_COMPLETED and the session then goes IDLE — it never self-
        # terminates, so SESSION_TERMINATED never fires on that happy path.
        # Subscribing to BOTH means a plain turn doesn't hang here; setdefault
        # lets a real SESSION_TERMINATED error reason win even if TURN_COMPLETED
        # raced in first.  (Mirrors run_ephemeral terminal detection, PR #316.)
        outcome.setdefault("reason", getattr(ev, "reason", None) or "natural")
        if getattr(ev, "error_type", None):
            outcome["error_type"] = ev.error_type
        if getattr(ev, "error_summary", None):
            outcome["error_summary"] = ev.error_summary
        done.set()

    def on_output(ev):
        text = getattr(ev, "text", "") or getattr(ev, "content", "")
        if text:
            print(text, end="", flush=True)

    client.subscribe(EventType.AGENT_OUTPUT, on_output)
    client.subscribe_once(EventType.SESSION_TERMINATED, on_done)
    client.subscribe_once(EventType.TURN_COMPLETED, on_done)

    # Inline spec — swap for profile="<name>", agent="<name>" to use a set.
    sid = await client.create_session(
        profile={"model": MODEL, "provider": PROVIDER}, timeout=60.0)
    if not sid:
        print("session.new failed — check provider auth / the daemon log")
        await client.disconnect()
        return 1

    await client.send_message("Who are you? Reply in one sentence.")
    await done.wait()
    print()
    if outcome.get("reason") == "error":
        print(f"error: {outcome.get('error_type')}: {outcome.get('error_summary')}")
        await client.disconnect()
        return 1
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


FIRE_TEMPLATE = _COMMON_HEADER + '''

async def main() -> int:
    """Fire-and-forget: send one message, do NOT wait for completion."""
    client = _new_client()
    if not await client.connect(timeout=120.0):
        print("could not connect/autostart the daemon — run the doctor")
        return 1
    sid = await client.create_session(
        profile={"model": MODEL, "provider": PROVIDER}, timeout=60.0)
    if not sid:
        await client.disconnect()
        return 1
    await client.send_message("Kick off the long-running task.")
    # Fire-and-forget: the session keeps running daemon-side after we leave.
    # (Reattach later with another client, or use the observer archetype.)
    await client.disconnect()
    print(f"dispatched to session {sid}; not waiting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


CASCADE_TEMPLATE = _COMMON_HEADER + '''
import uuid

# Each stage: (profile_name_or_spec, agent_or_None, trigger_prompt).
# Edit this worklist; a real cascade reads it from your orchestration.
WORKLIST = [
    ({"model": MODEL, "provider": PROVIDER}, None, "Stage 1: do the first thing."),
    ({"model": MODEL, "provider": PROVIDER}, None, "Stage 2: do the next thing."),
]


async def _run_stage(client, cascade_id, profile, agent, prompt) -> str:
    """Run one stage to terminal completion; return its reason.

    Each stage MUST be completion-gated — its persona calls
    ``signal_completion`` as its last action.  That is what emits
    ``SESSION_TERMINATED`` (the signal we wait on here) AND releases the
    shared warm slot so the NEXT stage can reuse it.  A non-gated stage
    would emit only ``TURN_COMPLETED``, never terminate, and stall the
    cascade — so unlike the single-shot ``client`` archetype, this stage
    intentionally waits on ``SESSION_TERMINATED`` only.
    """
    done = asyncio.Event()
    outcome = {}

    def on_done(ev):
        outcome["reason"] = getattr(ev, "reason", None)
        outcome["error_summary"] = getattr(ev, "error_summary", None)
        done.set()

    client.subscribe_once(EventType.SESSION_TERMINATED, on_done)
    sid = await client.create_session(
        profile=profile, agent=agent,
        cascade_driver_id=cascade_id,   # shared slot → warm imports across stages
        timeout=60.0)
    if not sid:
        return "spawn_failed"
    await client.send_message(prompt)
    await done.wait()
    return outcome.get("reason") or "unknown"


async def main() -> int:
    """Multi-session cascade driver — sequential stages sharing one warm slot."""
    client = _new_client()
    if not await client.connect(timeout=120.0):
        print("could not connect/autostart the daemon — run the doctor")
        return 1
    cascade_id = uuid.uuid4().hex   # one ID per cascade; stages reuse the slot
    for i, (profile, agent, prompt) in enumerate(WORKLIST, 1):
        reason = await _run_stage(client, cascade_id, profile, agent, prompt)
        print(f"stage {i}: {reason}")
        if reason == "error":
            await client.disconnect()
            return 1
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


OBSERVER_TEMPLATE = _COMMON_HEADER + '''

# The cascade tenant ID to observe — pass the SAME id the cascade driver used.
CASCADE_ID = "__CASCADE_ID__"


async def main() -> int:
    """Attach to a running cascade and live-trace its events (read-only)."""
    client = _new_client()
    if not await client.connect(timeout=120.0):
        print("could not connect/autostart the daemon — run the doctor")
        return 1
    print(f"observing cascade {CASCADE_ID} — Ctrl-C to stop")
    # cascade_events filters to the listed type-names; None = everything.
    async for ev in client.cascade_events(
        CASCADE_ID,
        event_types=["tool.call_start", "turn.completed",
                     "agent.completed", "session.terminated"],
        role="observer",
    ):
        et = getattr(ev, "type", "?")
        # Every event carries session_id (protocol 1.2+), stamped by the
        # daemon as it routes.  It is what tells two sessions of one
        # cascade apart -- agent_id will NOT: it is "main" for every
        # top-level session, so siblings are indistinguishable by it.
        #
        # Read it as a plain attribute, not getattr(ev, "session_id", "").
        # That idiom returns "" both when the field is missing and when
        # it is blank, so it cannot tell "this event type has no
        # attribution" from "this event was not routed" -- and against a
        # pre-1.2 server it silently prints empty for every line rather
        # than failing where you can see it.
        print(f"[{et}] session={ev.session_id or '<unrouted>'}")
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


HOST_TOOLS_TEMPLATE = _COMMON_HEADER + '''

# A client-provided ("host") tool: the AGENT calls it; YOUR client executes it
# locally and returns the result.  Register it BEFORE create_session so its
# schema reaches the runner-tier model (mid-session registration isn't seen yet).
def _send_to_user(args):
    """Tool body — runs in THIS process when the agent invokes the tool."""
    text = args.get("text", "")
    print(f"\\n[host tool] send_to_user({text!r})")
    return {"delivered": True, "text": text}


async def main() -> int:
    client = _new_client()
    if not await client.connect(timeout=120.0):   # cold autostart ~30-60s
        print("could not connect/autostart the daemon — run the doctor")
        return 1

    # Register host tools BEFORE the session so the runner-tier model sees them.
    await client.register_client_tools([{
        "name": "send_to_user",
        "description": "Send a text message to the user.",
        "parameters": {
            "type": "object",
            "properties": {"text": {"type": "string"}},
            "required": ["text"],
        },
        "handler": _send_to_user,   # runs locally when the agent calls the tool
    }])

    done = asyncio.Event()

    def on_done(ev):
        # Wake on whichever terminal lands first — a plain turn emits only
        # TURN_COMPLETED (then goes IDLE), a completion-gated one emits
        # SESSION_TERMINATED.  Subscribing to both avoids a hang on the plain
        # path.  (Mirrors run_ephemeral terminal detection, jaato PR #316.)
        done.set()

    def on_output(ev):
        text = getattr(ev, "text", "") or getattr(ev, "content", "")
        if text:
            print(text, end="", flush=True)

    client.subscribe(EventType.AGENT_OUTPUT, on_output)
    client.subscribe_once(EventType.SESSION_TERMINATED, on_done)
    client.subscribe_once(EventType.TURN_COMPLETED, on_done)

    sid = await client.create_session(
        profile={"model": MODEL, "provider": PROVIDER}, timeout=60.0)
    if not sid:
        print("session.new failed — check provider auth / the daemon log")
        await client.disconnect()
        return 1

    await client.send_message("Use the send_to_user tool to greet the user.")
    await done.wait()
    print()
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


TEMPLATES = {
    "host-tools": ("HOST_TOOLS_TEMPLATE", HOST_TOOLS_TEMPLATE,
                   "Client-provided ('host') tools — the agent calls a tool YOUR client runs."),
    "client": ("CLIENT_TEMPLATE", CLIENT_TEMPLATE,
               "Minimal jaato SDK client — single session, send + wait."),
    "fire": ("FIRE_TEMPLATE", FIRE_TEMPLATE,
             "Fire-and-forget jaato SDK client — send, do not wait."),
    "cascade": ("CASCADE_TEMPLATE", CASCADE_TEMPLATE,
                "Cascade driver — sequential multi-session stages."),
    "observer": ("OBSERVER_TEMPLATE", OBSERVER_TEMPLATE,
                 "Cascade observer — attach + live-trace events (read-only)."),
}
