"""Runnable SDK-client templates for ``jaato-scaffold new <archetype>``.

Each template bakes in the verified known-good recipe (the hard-won lessons
from the LORA-specialist transcript), so a generated client doesn't repeat the
hour of trial-and-error:

- ``IPCClient(client_type=ClientType.API)`` — **load-bearing**: the daemon
  keeps ``signal_completion`` for API clients (strips it for TERMINAL/WEB/CHAT
  roots), so headless completion works.
- ``connect(timeout=120.0)`` — a COLD daemon autostart takes ~30-60s; the SDK
  default (5s) is too low.
- ``env_file`` is always a real path — ``env_file=None`` crashes the IPC
  handshake with an opaque ``os.PathLike`` TypeError.
- completion via ``subscribe_once(EventType.SESSION_TERMINATED)`` then wait —
  the canonical signal (``reason`` ``natural``/``error``; ``error_summary`` /
  ``error_type`` populated on error).  NOT ``set_event_callback`` (which does
  not exist — the phantom method that ate the peer's tracing).

Templates use ``__TOKEN__`` placeholders filled by ``str.replace`` so the
embedded Python (dict literals, async braces) needs no escaping.
"""

ENV_TEMPLATE = """\
# Generated by `jaato-scaffold new`. A real .env is REQUIRED — the IPC
# handshake crashes on env_file=None.  Fill the provider key (or use a
# pass:// URI in the profile's plugin_configs instead of a raw key here).
JAATO_PROVIDER=__PROVIDER__
MODEL_NAME=__MODEL__
# __KEY_ENV__=<your key>   # or store via the provider's auth command
"""


_COMMON_HEADER = '''#!/usr/bin/env python3
"""__TITLE__

Generated by `jaato-scaffold new __ARCHETYPE__`.
Preflight first:
  python -m jaato_sdk.doctor --workspace __WORKSPACE__ --env-file __ENV_FILE__
"""
import asyncio
from jaato_sdk import __CLIENT_CLASS__, ClientType, EventType

SOCKET = "__SOCKET__"
ENV_FILE = "__ENV_FILE__"
WORKSPACE = "__WORKSPACE__"
MODEL = "__MODEL__"
PROVIDER = "__PROVIDER__"


__ON_STATUS_DEF__def _new_client():
    """Construct the API client with the known-good knobs."""
    return __CLIENT_CLASS__(
        SOCKET,
        client_type=ClientType.API,   # load-bearing: keeps signal_completion
        auto_start=True,
        env_file=ENV_FILE,            # never None (handshake crashes on None)
        workspace_path=WORKSPACE,__ON_STATUS_ARG__
    )
'''


CLIENT_TEMPLATE = _COMMON_HEADER + '''

async def main() -> int:
    client = _new_client()
    if not await client.connect(timeout=120.0):   # cold autostart ~30-60s
        print("could not connect/autostart the daemon — run the doctor")
        return 1

    done = asyncio.Event()
    outcome = {}

    def on_done(ev):
        outcome["reason"] = getattr(ev, "reason", None)
        outcome["error_type"] = getattr(ev, "error_type", None)
        outcome["error_summary"] = getattr(ev, "error_summary", None)
        done.set()

    def on_output(ev):
        text = getattr(ev, "text", "") or getattr(ev, "content", "")
        if text:
            print(text, end="", flush=True)

    client.subscribe(EventType.AGENT_OUTPUT, on_output)
    client.subscribe_once(EventType.SESSION_TERMINATED, on_done)

    # Inline spec — swap for profile="<name>", agent="<name>" to use a set.
    sid = await client.create_session(
        profile={"model": MODEL, "provider": PROVIDER}, timeout=60.0)
    if not sid:
        print("session.new failed — check provider auth / the daemon log")
        await client.disconnect()
        return 1

    await client.send_message("Who are you? Reply in one sentence.")
    await done.wait()
    print()
    if outcome.get("reason") == "error":
        print(f"error: {outcome.get('error_type')}: {outcome.get('error_summary')}")
        await client.disconnect()
        return 1
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


FIRE_TEMPLATE = _COMMON_HEADER + '''

async def main() -> int:
    """Fire-and-forget: send one message, do NOT wait for completion."""
    client = _new_client()
    if not await client.connect(timeout=120.0):
        print("could not connect/autostart the daemon — run the doctor")
        return 1
    sid = await client.create_session(
        profile={"model": MODEL, "provider": PROVIDER}, timeout=60.0)
    if not sid:
        await client.disconnect()
        return 1
    await client.send_message("Kick off the long-running task.")
    # Fire-and-forget: the session keeps running daemon-side after we leave.
    # (Reattach later with another client, or use the observer archetype.)
    await client.disconnect()
    print(f"dispatched to session {sid}; not waiting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


CASCADE_TEMPLATE = _COMMON_HEADER + '''
import uuid

# Each stage: (profile_name_or_spec, agent_or_None, trigger_prompt).
# Edit this worklist; a real cascade reads it from your orchestration.
WORKLIST = [
    ({"model": MODEL, "provider": PROVIDER}, None, "Stage 1: do the first thing."),
    ({"model": MODEL, "provider": PROVIDER}, None, "Stage 2: do the next thing."),
]


async def _run_stage(client, cascade_id, profile, agent, prompt) -> str:
    """Run one stage to terminal completion; return its reason."""
    done = asyncio.Event()
    outcome = {}

    def on_done(ev):
        outcome["reason"] = getattr(ev, "reason", None)
        outcome["error_summary"] = getattr(ev, "error_summary", None)
        done.set()

    client.subscribe_once(EventType.SESSION_TERMINATED, on_done)
    sid = await client.create_session(
        profile=profile, agent=agent,
        cascade_driver_id=cascade_id,   # shared slot → warm imports across stages
        timeout=60.0)
    if not sid:
        return "spawn_failed"
    await client.send_message(prompt)
    await done.wait()
    return outcome.get("reason") or "unknown"


async def main() -> int:
    """Multi-session cascade driver — sequential stages sharing one warm slot."""
    client = _new_client()
    if not await client.connect(timeout=120.0):
        print("could not connect/autostart the daemon — run the doctor")
        return 1
    cascade_id = uuid.uuid4().hex   # one ID per cascade; stages reuse the slot
    for i, (profile, agent, prompt) in enumerate(WORKLIST, 1):
        reason = await _run_stage(client, cascade_id, profile, agent, prompt)
        print(f"stage {i}: {reason}")
        if reason == "error":
            await client.disconnect()
            return 1
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


OBSERVER_TEMPLATE = _COMMON_HEADER + '''

# The cascade tenant ID to observe — pass the SAME id the cascade driver used.
CASCADE_ID = "__CASCADE_ID__"


async def main() -> int:
    """Attach to a running cascade and live-trace its events (read-only)."""
    client = _new_client()
    if not await client.connect(timeout=120.0):
        print("could not connect/autostart the daemon — run the doctor")
        return 1
    print(f"observing cascade {CASCADE_ID} — Ctrl-C to stop")
    # cascade_events filters to the listed type-names; None = everything.
    async for ev in client.cascade_events(
        CASCADE_ID,
        event_types=["tool.call_start", "turn.completed",
                     "agent.completed", "session.terminated"],
        role="observer",
    ):
        et = getattr(ev, "type", "?")
        sid = getattr(ev, "session_id", "")
        print(f"[{et}] session={sid}")
    await client.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
'''


TEMPLATES = {
    "client": ("CLIENT_TEMPLATE", CLIENT_TEMPLATE,
               "Minimal jaato SDK client — single session, send + wait."),
    "fire": ("FIRE_TEMPLATE", FIRE_TEMPLATE,
             "Fire-and-forget jaato SDK client — send, do not wait."),
    "cascade": ("CASCADE_TEMPLATE", CASCADE_TEMPLATE,
                "Cascade driver — sequential multi-session stages."),
    "observer": ("OBSERVER_TEMPLATE", OBSERVER_TEMPLATE,
                 "Cascade observer — attach + live-trace events (read-only)."),
}
