"""The completion GATE as one set — what ``new sweep`` emits alongside its client.

:mod:`_processor_template` emits the gate's *middle*: a ``validate`` with the
bounded-refusal contract already right.  It then PRINTS the profile wiring and
stops, which leaves the author holding the two ends — the checks the gate runs,
and the profile keys that make the gate reachable at all.  This module emits
those ends, so a sweep arrives with a working gate rather than with one file and
the relationship between three (jaato #772).

WHY THE SWEEP ARCHETYPE SPECIFICALLY.  A sweep's whole shape is "N agents
attempt the same task, then compare".  Its arms are graded, so "did this arm
actually meet the criteria" is not a nicety, it is the measurement.  Every other
archetype can reasonably end a turn and be done; a sweep that cannot tell a
finished arm from an arm that claimed to be finished is not measuring anything.

THE THREE FILES, AND WHY NONE OF THEM WORKS ALONE:

``acceptance.sh``
    The checks.  Run by the in-session gate AND by whatever grades the run
    afterwards, because two scripts can end up grading different things and one
    script can only be right or wrong (#768 rule 8).

``.jaato/scripts/processors/<name>.py``
    The in-session gate — :mod:`_processor_template`, emitted with
    ``CHECKS_COMMAND`` already pointing at ``acceptance.sh`` instead of at the
    ``None`` a reader has to notice and fill.

``.jaato/profiles/<name>.yaml``
    ``completion_processors:`` (which runs the gate) and
    ``completion_payload_schema:`` (without which there is nothing to gate —
    see below).  Plus ``.jaato/completion_schemas/<name>.json``, the schema that
    key points at.

THE SCHEMA IS NOT DECORATION.  ``LifecycleTools._should_hide_signal_completion``
hides ``signal_completion`` outright when the profile declares no
``completion_payload_schema`` — gate 1, applying to root and subagent sessions
alike.  So a profile with ``completion_processors:`` and no schema does not have
a lenient gate, it has no gate and no ``signal_completion``: the agent cannot
signal, the processor never runs, and the sweep driver's ``complete()`` waits
for a payload that cannot arrive.  Emitting the two keys together is the
difference between a pattern and a footgun.
``tests/test_scaffold_sweep_gate_contract.py`` reads that method rather than
restating it, so the claim cannot outlive the behaviour.

HOW THE UNCONFIGURED STATE BEHAVES, AND WHY IT IS THE INTERESTING CASE.  The
emitted ``acceptance.sh`` ships with no checks in it — the generator does not
know what your task's acceptance criteria are, any more than ``profile-set``
guesses a plugin set.  The tempting thing is for a script with nothing to check
to exit 0.  That is the defect class #768 rule 5 is about: an error path
returning the same value as success, which here means a gate that is not
configured reads as a gate that PASSED, and every arm is waved through.

So it exits 78 (``EX_CONFIG``) and says so on **stderr**, printing nothing on
stdout.  The emitted processor's own broken-gate discrimination — non-zero exit
with empty stdout means the checker never got as far as checking — then routes
that to ``faults[]``: it blocks, and it spends no refusal, because no fix the
agent makes will configure your acceptance criteria for you.  The generated set
therefore fails CLOSED out of the box, loudly, at the author.  That is what the
emit-then-check in ``build.py`` asserts.
"""

from __future__ import annotations

import json
from typing import Optional

#: Exit status ``acceptance.sh`` uses for "nobody configured me".
#:
#: ``EX_CONFIG`` from ``sysexits.h``.  Distinct from 1 (checks ran and failed)
#: because the two are different events and the gate treats them differently:
#: a failing check is a wrong answer that spends a refusal, an unconfigured
#: script is an environment fault that does not.
EX_CONFIG = 78

#: The name used when ``--gate-name`` is not given.  Also the module stem, the
#: schema stem, the profile stem and the processor entry's ``name:`` — one name
#: across the set, so the four files are visibly one thing.
DEFAULT_GATE_NAME = "acceptance"

#: How the gate invokes the checks.  ``--all`` is the mode whose contract the
#: processor depends on: one line per failure on stdout, nothing on success.
CHECKS_COMMAND = "./acceptance.sh --all"


ACCEPTANCE_SH_TEMPLATE = '''#!/usr/bin/env sh
# acceptance.sh — the acceptance checks for this sweep.
#
# Generated by `__PROVENANCE__`.
#
# ONE SCRIPT, TWO CALLERS.  The in-session gate
# (.jaato/scripts/processors/__NAME__.py) runs this to decide whether an arm may
# signal completion; whatever grades the sweep afterwards runs the SAME script
# to score it.  That is deliberate: two scripts can end up grading different
# things — the gate passing an arm the scoreboard then fails — and one script
# can only be right or wrong.
#
# THE --all CONTRACT.  The gate reads this script's output as the failure list,
# so the three channels are not interchangeable:
#
#   stdout  ONE LINE PER FAILING CHECK, and NOTHING AT ALL on success.
#           Each line is handed verbatim to a model that is about to try
#           again, so write it as an instruction, not as a log entry.
#   exit    0 when every check passed; 1 when any failed; __EX_CONFIG__ when
#           there is nothing configured to check (see below).
#   stderr  diagnostics for a human.  The gate does not read stderr as
#           failures, so anything you print here is invisible to the agent.
#
# WHY AN UNCONFIGURED SCRIPT DOES NOT EXIT 0.  As emitted, `run_checks` below
# is empty — the generator cannot know your acceptance criteria.  A script with
# nothing to check that exits 0 is an error path returning the same value as
# success: the gate would read "no failures" and wave every arm through, and a
# sweep whose gate is not running still reports every arm as having met the
# criteria.  So it exits __EX_CONFIG__ with an empty stdout, which the
# processor recognises as "the checker did not run" and reports as an
# environment fault — blocking, but costing the agent none of its retries,
# because no fix it makes will configure this file.
#
# ADD YOUR CHECKS to `run_checks`, then this exits 0/1 like a normal gate.

set -u

MODE=""
CASE_ID="${JAATO_CASE_ID:-}"

for arg in "$@"; do
    case "$arg" in
        --all)  MODE="all" ;;
        --help) MODE="help" ;;
        --*)
            printf 'acceptance.sh: unknown option %s\\n' "$arg" >&2
            exit 64
            ;;
        *)      CASE_ID="$arg" ;;
    esac
done

if [ "$MODE" = "help" ]; then
    printf 'usage: acceptance.sh --all [CASE_ID]\\n' >&2
    printf '  --all      report every failing check (one line each) on stdout\\n' >&2
    printf '  CASE_ID    also run acceptance/<CASE_ID>.sh; defaults to $JAATO_CASE_ID\\n' >&2
    exit 0
fi

if [ "$MODE" != "all" ]; then
    printf 'acceptance.sh: --all is required (it is the mode the gate uses)\\n' >&2
    exit 64
fi

HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

failures=0
checks_run=0

# Report ONE failing check.  Goes to stdout because stdout is the failure list.
#
# Write the message as the instruction you want the agent to act on — it is
# read by a model about to retry, not by a human reading a log.  The framework
# appends how many attempts remain, so do not write that here.
fail() {
    printf '%s\\n' "$1"
    failures=$((failures + 1))
}

# Run ONE check: `check "<message when it fails>" <command...>`.
#
# The command's own output is discarded — a check reports by its exit status,
# and letting it write to stdout would inject non-failure lines into the list
# the gate parses.  Redirect to stderr yourself if you want to see it.
check() {
    _msg="$1"
    shift
    checks_run=$((checks_run + 1))
    if ! "$@" >/dev/null 2>&1; then
        fail "$_msg"
    fi
}

# EDIT THIS.  One `check` per acceptance criterion, e.g.
#
#     check "the test suite does not pass yet — run it, fix what fails, commit" \\
#           sh -c 'pytest -q'
#
#     check "src/ still contains a TODO marker; finish or remove it" \\
#           sh -c '! grep -rq TODO src/'
#
# Keep each message actionable and specific to the criterion it guards: it is
# the whole of what the agent is told about that failure.
run_checks() {
    :
}

# The per-case tier.  Keeps this file task-agnostic while the gate stays
# specific: generic criteria live above, and anything true of only ONE case
# lives in acceptance/<CASE_ID>.sh, which is sourced here and calls the same
# `check` helper.  The gate and the graders select the same case the same way,
# so they cannot diverge on which criteria applied.
run_case_checks() {
    [ -n "$CASE_ID" ] || return 0
    _case_script="$HERE/acceptance/$CASE_ID.sh"
    [ -f "$_case_script" ] || return 0
    # shellcheck source=/dev/null
    . "$_case_script"
}

run_checks
run_case_checks

if [ "$checks_run" -eq 0 ]; then
    # NOT exit 0.  See the header: nothing configured is not "everything
    # passed", and an empty stdout with a non-zero exit is what tells the gate
    # the checks did not run.
    printf 'acceptance.sh: no checks are configured — add them to run_checks\\n' >&2
    printf '  (or to acceptance/<CASE_ID>.sh). Refusing to report success for\\n' >&2
    printf '  checks that never ran.\\n' >&2
    exit __EX_CONFIG__
fi

[ "$failures" -eq 0 ] || exit 1
exit 0
'''


#: The completion payload schema.  Kept as a dict rather than a JSON string so
#: the emitted file is produced by ``json.dumps`` — a schema that is generated
#: as text is one typo away from being invalid JSON, and this one is load-
#: bearing (a schema that fails to load is a session with no
#: ``signal_completion`` at all).
#:
#: ``errors`` and ``warnings`` are the escape hatches every completion schema in
#: this tree carries (``docs/design/payload-schema-conventions.md``), and for a
#: sweep they are not optional decoration: the emitted driver reads
#: ``payload["errors"]`` to separate an arm that FAILED from an arm that could
#: not RUN.  Without the field the driver's check reads an absent key and every
#: blocked arm is scored as a result.
#:
#: All three are ``required`` with ``additionalProperties: false`` — the shape
#: strict-mode tool sampling needs (see the ``strict_tools`` note in CLAUDE.md),
#: and it makes "no errors" something the agent states rather than omits.
def _schema_dict(name: str) -> dict:
    """The completion payload schema emitted for gate *name*."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": f"{name} completion payload",
        "description": (
            "What one sweep arm must produce to signal completion. The "
            f"{name} completion processor gates this payload against "
            "acceptance.sh before it is accepted."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": ["summary", "errors", "warnings"],
        "properties": {
            "summary": {
                "type": "string",
                "description": (
                    "What you did, in a few sentences. Read by a human "
                    "comparing this arm against the others."
                ),
            },
            "errors": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Anything that stopped you doing the work: a tool that "
                    "kept failing, a fault the environment would not clear, "
                    "an instruction you could not carry out. Empty list when "
                    "there were none. Report here rather than describing a "
                    "run as clean — the driver reads a non-empty errors[] as "
                    "'this arm could not be measured', which is a different "
                    "verdict from 'this arm did the work badly' and is the "
                    "only way to say the first one."
                ),
            },
            "warnings": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Caveats that did NOT stop you: an assumption you had to "
                    "make, a check you could not fully verify. Empty list "
                    "when there were none. These never block, so reporting "
                    "one costs you nothing."
                ),
            },
        },
    }


PROFILE_TEMPLATE = '''# __NAME__ — the gated arm of this sweep.
#
# Generated by `__PROVENANCE__`.
#
# THE TWO KEYS AT THE BOTTOM ARE ONE UNIT.  completion_processors runs the
# gate; completion_payload_schema is what makes there be anything to gate.
# Without the schema, LifecycleTools._should_hide_signal_completion hides
# signal_completion from the session entirely — so the agent cannot signal,
# the processor never runs, and a driver calling complete() waits for a
# payload that can never arrive.  Deleting the schema does not loosen this
# gate, it removes it.
name: __NAME__
description: >-
  One arm of a sweep, gated on acceptance.sh. Its completion is refused until
  the checks pass, or until the refusal ceiling is reached.

# Choose these yourself — the generator does not guess a plugin set.
# `jaato-scaffold explain plugins` lists what is installed.  An arm that has to
# CHANGE something needs at least file_edit and cli; one that only inspects
# does not.
plugins: []
__BINDING__
# The typed contract for what an arm produces.  Also the reason
# signal_completion exists at all in this session — see the note above.
completion_payload_schema: completion_schemas/__NAME__.json

# The gate.  `jaato-scaffold explain completion` documents every key.
completion_processors:
  - script: scripts/processors/__NAME__.py
    name: __NAME__
    on_error: fail_completion
    # HOW MANY TIMES THIS GATE MAY BLOCK, then what happens.  The framework
    # counts, per session, on state it owns; the processor holds no counter.
    # Unbounded is the default elsewhere and does not terminate on its own —
    # the processor refuses, the agent re-claims completion, forever (an
    # observed run spent seven refusals in 156 seconds on the same two errors
    # and ended with its whole budget gone).  A graded sweep wants a ceiling.
    max_refusals: 3
    # At the ceiling: `allow` lets the unfinished completion stand, on the
    # reasoning that a FAIL verdict carries information and a BLOCKED arm
    # carries none — the checks still failed and the graders still say so.
    # Use `fail` when an unfinished completion is worse than none.
    on_exhausted: allow
'''


def render_acceptance_sh(name: str, provenance: str) -> str:
    """The ``acceptance.sh`` the gate and the graders share.

    Args:
        name: The gate name, used to point the reader at the processor module
            that runs this script.
        provenance: The command that generated it.

    Returns:
        POSIX-``sh`` source.  Emitted executable by the caller — a checks
        script the gate cannot exec is an environment fault on every arm.
    """
    return (ACCEPTANCE_SH_TEMPLATE
            .replace("__EX_CONFIG__", str(EX_CONFIG))
            .replace("__PROVENANCE__", provenance)
            .replace("__NAME__", name))


def render_schema(name: str) -> str:
    """The completion payload schema, as the JSON that lands on disk."""
    return json.dumps(_schema_dict(name), indent=2) + "\n"


def render_profile(name: str, provenance: str,
                   provider: Optional[str] = None,
                   model: Optional[str] = None) -> str:
    """The profile carrying the gate's two keys.

    Args:
        name: The gate name — the profile stem, the schema stem, the processor
            module stem and the entry's ``name:``.
        provenance: The command that generated it.
        provider: Bound into the profile when ``new sweep`` was given one.
        model: Likewise.  Both or neither — ``build.py`` refuses half a
            binding before reaching here.

    Returns:
        YAML source.

    Note:
        With no binding the profile names no model, which is correct rather
        than incomplete: the sweep archetype's provider/model flags are
        optional precisely because a profile SET is expected to supply them,
        and writing a provider nobody chose would read as guidance rather than
        as the throwaway it is.  The emitted comment says so.
    """
    if provider and model:
        binding = (f"\n# Bound from the flags `new sweep` was given.\n"
                   f"model: {model}\n"
                   f"provider: {provider}\n")
    else:
        binding = ("\n# No model/provider: pass --provider/--model to `new "
                   "sweep` to bind them\n# here, or inherit them from a "
                   "profile set (`jaato-scaffold explain sets`).\n")
    return (PROFILE_TEMPLATE
            .replace("__BINDING__", binding)
            .replace("__PROVENANCE__", provenance)
            .replace("__NAME__", name))
