"""The completion-processor template for ``jaato-scaffold new processor``.

The output-side counterpart to :mod:`_client_templates`: where those bake in
the verified recipe for driving a session, this bakes in the verified recipe
for GATING one — the parts of a ``completion_processors`` module that are easy
to get wrong and expensive to get wrong late (jaato #768, #769).

Why a generator and not just documentation: a hand-written processor got every
one of the four below wrong on its first pass, in a session where the same
error class also produced a grader read as a pass and a failed ``git diff``
read as "nothing changed".  A template encodes a contract; a docstring merely
asserts one.

What the emitted module gets right, and what each cost when it was absent:

1. **The refusal ceiling is DECLARED, not hand-rolled.**  The emitted wiring
   carries ``max_refusals`` / ``on_exhausted`` and the module holds no counter
   of its own.  Before those keys existed authors kept one in a module-level
   global, which worked only on the undocumented guarantee that processors are
   loaded once per session — so the ceiling would have vanished silently the
   day that changed.  A generator emitting the folklore would codify exactly
   what #768 set out to retire.
2. **The environment-fault split.**  A missing checks script or an absent
   parameter is not a wrong answer, and phrasing one as a retryable error
   burns the whole budget without ever producing a verdict.  Those go to
   ``faults[]``, which is budget-exempt.
3. **Never ``[]`` on a broken gate.**  The emitted subprocess gate reads a
   non-zero exit with empty output as "the checking script itself broke" —
   because with ``--all`` semantics stdout IS the error list, so empty stdout
   plus failure means the check never ran.  Returning ``[]`` there waves the
   completion through on a gate that is not running.
4. **Return strings written as instructions for the retry.**  They are read by
   a model about to try again, not by a human reading a log.  The framework
   appends the attempts remaining, so the module says what is wrong and what
   to do about it.

Placeholders are ``__TOKEN__``-style, filled by ``str.replace``, so the
embedded Python needs no escaping.
"""

#: The generated processor module.
PROCESSOR_TEMPLATE = '''"""__NAME__ — a completion processor (gates signal_completion).

Generated by `__PROVENANCE__`.

WIRE IT into the profile whose completions it should gate:

__WIRING__

Then: jaato-scaffold explain completion

WHAT RUNS WHEN.  The agent calls signal_completion; the framework validates
the payload against completion_payload_schema; then this module's `validate`
runs.  A non-empty `errors` blocks the completion and hands the agent every
string, so it fixes and signals again — inside the session's own max_turns,
which IS the retry budget.  There is no second attempts knob.

THE FOUR CHANNELS of the return, and the reason there are four:

    errors      blocks; SPENDS one refusal per call.  A wrong answer.
    faults      blocks once per session; spends NOTHING.  An environment
                fault the agent's next attempt cannot clear.
    warnings    never blocks.  For the audit trail.
    incomplete  never blocks; gates is_complete on a phase:"completeness"
                processor.  "Valid so far, but not done."

The split between the first two is what keeps the loop honest: a retryable
message about an unfixable fault spends the whole budget and still produces
no verdict.
"""

from __future__ import annotations

import shlex
import subprocess
from pathlib import Path
from typing import Any, Dict, List

from jaato_sdk.cascade_authoring import ProcessorResult

#: The external check to run, or None to skip that gate.
#:
#: EDIT THIS.  A shell command run from the workspace root that prints ONE
#: LINE PER FAILURE to stdout and nothing on success — `pytest -q`, a
#: lint runner, an acceptance script.  With those semantics stdout IS the
#: error list, which is what makes the broken-gate discrimination below
#: possible.
#:
#: Run the SAME script your post-hoc graders run.  Two scripts cannot end
#: up grading different things; one script can only be right or wrong.
CHECKS_COMMAND: str | None = None

#: Seconds before the check is abandoned.  A timeout is an environment
#: fault, not a wrong answer — see `_run_checks`.
CHECKS_TIMEOUT = 300


def _run_checks(workspace: str) -> ProcessorResult:
    """Run CHECKS_COMMAND; map its outcome onto the channels.

    The discrimination this function exists for:

    - exit 0                      → the checks pass.  No objection.
    - non-zero WITH output        → real failures; one error per line.
                                    These are wrong answers and spend a
                                    refusal.
    - non-zero with NO output     → the checking script itself broke.  The
                                    gate did not RUN, so it must not read
                                    as a gate that PASSED.  Blocking, and
                                    a fault rather than an error: no fix
                                    the agent makes will clear it.
    - missing / timed out         → same reasoning; a fault.

    That third case is the one worth staring at.  Returning `[]` there —
    the obvious thing, since there were no failure lines — is an error path
    producing the same value as success, which is how a completion gets
    waved through on a check that never ran.

    Args:
        workspace: Session workspace root; the command's cwd.

    Returns:
        A ProcessorResult carrying `errors` and/or `faults`.
    """
    if not CHECKS_COMMAND:
        return {}
    try:
        proc = subprocess.run(
            shlex.split(CHECKS_COMMAND),
            cwd=workspace, capture_output=True, text=True,
            timeout=CHECKS_TIMEOUT,
        )
    except FileNotFoundError:
        return {"faults": [
            f"the check command {CHECKS_COMMAND!r} is not on PATH in this "
            f"workspace. This is an environment fault, not something your "
            f"fix can address: retrying will not clear it. Record it in the "
            f"payload's errors[] (or the nearest field your completion "
            f"schema offers) and signal completion again."
        ]}
    except subprocess.TimeoutExpired:
        return {"faults": [
            f"the check command {CHECKS_COMMAND!r} did not finish within "
            f"{CHECKS_TIMEOUT}s. This is an environment fault, not something "
            f"your fix can address. Record it in the payload's errors[] and "
            f"signal completion again."
        ]}
    if proc.returncode == 0:
        return {}
    failures = [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]
    if not failures:
        # Non-zero AND silent: stdout is the failure list, so an empty one
        # with a failing exit means the checker did not get as far as
        # checking.  NEVER return {} here.
        detail = (proc.stderr or "").strip()[:400] or "(no output)"
        return {"faults": [
            f"the check command {CHECKS_COMMAND!r} exited "
            f"{proc.returncode} without reporting any failures, so the "
            f"checks did not run. This is an environment fault, not a "
            f"failing check: retrying will not clear it. stderr: {detail}"
        ]}
    return {"errors": [
        f"{line}  — fix the underlying cause in the workspace, then call "
        f"signal_completion again. Do not report success while this fails."
        for line in failures
    ]}


def _check_claims_against_the_ledger(
    payload: Dict[str, Any], context: Any,
) -> List[str]:
    """Cross-check the payload against what the session ACTUALLY did.

    `context.tool_calls` is the framework's paired ledger of every
    function_call and its response — the one thing a completion processor
    can see that the model cannot rewrite.  A payload claiming success is
    a claim; the ledger is evidence.

    EDIT THIS.  The worked check here is the cheapest useful one: if any
    tool call failed and the payload reports no errors, the agent has
    claimed a clean run over a failure.  Replace it with whatever your
    completion schema actually promises.

    Args:
        payload: The agent's validated signal_completion payload.
        context: RenderContext — `tool_calls`, `agent_params`,
            `workspace_path`, `config_root`, `env`, `session_id`, `logger`.

    Returns:
        One instruction per discrepancy; empty when the payload is honest.
    """
    failed = [tc for tc in (context.tool_calls or []) if not tc.get("success")]
    if not failed:
        return []
    if payload.get("errors"):
        return []          # already reported them; nothing to correct
    names = ", ".join(sorted({str(tc.get("name")) for tc in failed}))
    return [
        f"{len(failed)} tool call(s) failed during this session ({names}) but "
        f"the payload reports no errors. Either retry them so they succeed, "
        f"or record what failed in errors[] — then call signal_completion "
        f"again. Do not report a clean run over a failure."
    ]


def validate(payload: Dict[str, Any], context: Any) -> ProcessorResult:
    """Gate signal_completion for this agent.

    Args:
        payload: The agent's signal_completion payload, already validated
            against the profile's completion_payload_schema.
        context: RenderContext (see `_check_claims_against_the_ledger`).

    Returns:
        A ProcessorResult. Empty (or all-empty channels) accepts the
        completion.

    Note:
        This module holds NO refusal counter. How many times it may block
        is `max_refusals:` on the profile entry, and what happens at the
        ceiling is `on_exhausted:`; the framework counts, on state it owns
        for the session. A counter here would be a second budget beside
        the framework's, and a global whose survival depends on a caching
        detail (jaato #768).
    """
    errors: List[str] = []
    faults: List[str] = []

    checks = _run_checks(getattr(context, "workspace_path", "") or ".")
    errors.extend(checks.get("errors", []))
    faults.extend(checks.get("faults", []))

    errors.extend(_check_claims_against_the_ledger(payload, context))

    return {"errors": errors, "faults": faults}
'''


#: The profile wiring the emitted module needs, printed after generation and
#: embedded in the module's own docstring so the two cannot drift.
WIRING_TEMPLATE = """completion_processors:
  - script: scripts/processors/__NAME__.py
    name: __NAME__
    on_error: fail_completion   # or `warn` to log without blocking
    max_refusals: 3             # this gate may block 3 times, then:
    on_exhausted: allow         # `allow` = let the unfinished completion
                                #   stand (a FAIL verdict carries
                                #   information; a BLOCKED arm carries
                                #   none), `fail` = keep blocking."""


def render(name: str, provenance: str) -> str:
    """The processor module for *name*, with its own wiring embedded.

    Args:
        name: The processor's name — the module stem and the entry's
            ``name:``.
        provenance: The command that generated it, reproduced in the
            module docstring.

    Returns:
        The complete module source.
    """
    wiring = "\n".join(
        "    " + line if line else ""
        for line in wiring_for(name).splitlines()
    )
    return (PROCESSOR_TEMPLATE
            .replace("__WIRING__", wiring)
            .replace("__PROVENANCE__", provenance)
            .replace("__NAME__", name))


def wiring_for(name: str) -> str:
    """The ``completion_processors:`` YAML block wiring *name* into a profile."""
    return WIRING_TEMPLATE.replace("__NAME__", name)
