"""The ``new`` verb — scaffold profile-sets (and SDK clients), then re-validate.

The defining property: whatever ``new`` emits, it runs straight back through
:mod:`validate` (the SAME validator the ``validate`` verb uses).  So scaffolded
output is valid **by construction** — there is no separate "is the generated
profile ok" path, and a generator bug that emits an unknown knob fails loudly
at scaffold time instead of being silently dropped at runtime.

``new`` also consults :mod:`introspect` while emitting — it only writes knobs
the target provider actually declares (e.g. ``api_key`` is emitted only if the
provider has an ``api_key`` top-level knob), so the emit step can't author a
key the validate step would then reject.

Fail-loud, no hardcoded fallbacks: required inputs (workspace / set / provider
/ model / agents) must be supplied; an unknown provider is a hard error, not a
guess.  Emitted base profiles carry ``plugins: []`` + a pointer to
``explain plugins`` rather than a guessed plugin set.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

from . import introspect
from . import validate as _validate


def _compose_env(provider: str, active: list) -> str:
    """Build a workspace .env: active settings + commented optional knobs.

    Lists, commented-out, the chosen provider's env vars (all — they're user
    provider config) and the framework knobs that have a MEANINGFUL literal
    default (the tunable ones; empty-default flags + framework-internal vars
    are left to `explain env`).  Discovered from installed code, so the list
    can't drift from what the daemon actually reads.
    """
    info = introspect.resolve_provider(provider)
    pdir = info.dir_name if info else provider
    EV = introspect.env_vars()
    # names already set in the active block — never re-emit them as knobs
    active_names = {ln.split("=", 1)[0].strip()
                    for ln in active if "=" in ln and not ln.startswith("#")}

    lines = ["# Generated by `jaato-scaffold new`.  Active settings below;",
             "# commented lines are optional knobs the daemon/plugins read",
             "# (see `jaato-scaffold explain env`).", ""]
    lines += active + [""]

    # the chosen provider's vars (all — they're user provider config)
    pvars = sorted(n for n, v in EV.items()
                   if v.category == f"provider:{pdir}" and n not in active_names)
    if pvars:
        lines.append(f"# ---- provider: {pdir} (uncomment + set as needed) ----")
        for n in pvars:
            lines.append(f"# {n}={EV[n].default or ''}")
        lines.append("")

    # all OTHER meaningfully-defaulted knobs (daemon + plugins), grouped by
    # category; OTHER providers excluded.  Empty-default flags + internal
    # vars (no meaningful default) are left to `explain env`.
    by_cat: Dict[str, list] = {}
    for n, v in EV.items():
        if v.category.startswith("provider:") or n in active_names:
            continue
        if v.default in (None, ""):
            continue
        by_cat.setdefault(v.category, []).append(n)
    for cat in sorted(by_cat):
        lines.append(f"# ---- {cat} knobs (defaults shown) ----")
        for n in sorted(by_cat[cat]):
            lines.append(f"# {n}={EV[n].default}")
        lines.append("")
    return "\n".join(lines)


def run(args) -> int:
    archetype = args.archetype
    if archetype in (None, "profile-set", "set"):
        return _new_profile_set(args)
    if archetype in ("client", "fire", "cascade", "observer", "host-tools"):
        return _new_client_archetype(args, archetype)
    print(f"unknown archetype {archetype!r} — one of: profile-set, client, "
          "fire, cascade, observer, host-tools")
    return 2


# --------------------------------------------------------- client archetypes

def _new_client_archetype(args, archetype: str) -> int:
    """Emit a runnable SDK client (+ .env), then py_compile it (emit-then-check).

    The client templates bake in the known-good recipe; we can't fully *run*
    them here (needs a live daemon + provider auth) so the build-time check is
    a syntax compile — the client analog of profile-set's emit-then-validate.
    Next step for the user is the doctor, which checks the runtime env.
    """
    import py_compile
    from ._client_templates import TEMPLATES

    missing = [f for f in ("workspace", "provider", "model")
               if not getattr(args, f, None)]
    if missing:
        print(f"new {archetype}: missing required --{' / --'.join(missing)}")
        return 2
    provider = args.provider
    if introspect.resolve_provider(provider) is None:
        known = ", ".join(sorted(introspect.providers()))
        print(f"new {archetype}: unknown provider '{provider}' (have: {known})")
        return 2

    ws = Path(args.workspace).resolve()
    ws.mkdir(parents=True, exist_ok=True)
    env_file = ws / ".env"
    py_file = ws / f"run_{archetype}.py"
    socket = "/tmp/jaato.sock"
    _, template, title = TEMPLATES[archetype]

    subs = {
        "__SOCKET__": socket,
        "__ENV_FILE__": str(env_file),
        "__WORKSPACE__": str(ws),
        "__MODEL__": args.model,
        "__PROVIDER__": provider,
        "__TITLE__": title,
        "__ARCHETYPE__": archetype,
        "__KEY_ENV__": f"JAATO_{provider.upper()}_API_KEY",
        "__CASCADE_ID__": "REPLACE_WITH_THE_CASCADE_DRIVER_ID",
    }
    # --recoverable: emit IPCRecoveryClient (auto-reconnect, survives daemon
    # restarts) instead of the plain IPCClient.  Applies to every archetype —
    # the long-lived ones (cascade/observer) benefit most.
    if getattr(args, "recoverable", False):
        subs["__CLIENT_CLASS__"] = "IPCRecoveryClient"
        subs["__ON_STATUS_DEF__"] = (
            "def _on_status(status):\n"
            "    # Reconnection lifecycle — IPCRecoveryClient auto-reconnects and\n"
            "    # survives daemon restarts (a per-run jaato-server --stop +\n"
            "    # autostart); IncompatibleServerError is treated as permanent.\n"
            "    print(f\"[connection] {getattr(status, 'state', status)}\")\n\n\n"
        )
        subs["__ON_STATUS_ARG__"] = "\n        on_status_change=_on_status,"
    else:
        subs["__CLIENT_CLASS__"] = "IPCClient"
        subs["__ON_STATUS_DEF__"] = ""
        subs["__ON_STATUS_ARG__"] = ""

    def _fill(text: str) -> str:
        for k, v in subs.items():
            text = text.replace(k, v)
        return text

    written = []
    if not env_file.exists() or args.force:
        env_file.write_text(_compose_env(provider, [
            f"JAATO_PROVIDER={provider}", f"MODEL_NAME={args.model}"]),
            encoding="utf-8")
        written.append(env_file.name)
    if py_file.exists() and not args.force:
        print(f"new {archetype}: {py_file} exists (use --force to overwrite)")
        return 2
    py_file.write_text(_fill(template), encoding="utf-8")
    written.append(py_file.name)

    print(f"scaffolded {archetype} client in {ws}:")
    for w in written:
        print(f"  + {w}")

    # emit-then-check: the generated client must at least compile.
    print("\ncompile-checking the generated client …")
    try:
        py_compile.compile(str(py_file), doraise=True)
    except py_compile.PyCompileError as e:
        print(f"✘ generated client does not compile — generator bug:\n{e}")
        return 1
    print("✓ generated client compiles.")
    print(f"\nnext:\n  python -m jaato_sdk.doctor --workspace {ws} "
          f"--env-file {env_file} --secret pass://jaato/{provider}/api-key\n"
          f"  python {py_file}")
    return 0


# ----------------------------------------------------------- profile-set

def _base_profile_yaml(agent: str) -> str:
    """Tier-1 provider-agnostic base profile — plugins left for the author."""
    return (
        f"# Tier-1 base for the '{agent}' stage — PROVIDER-AGNOSTIC.\n"
        f"# Holds stage determinism (plugins, schemas, permission policy).\n"
        f"# Active model + provider live in profiles/<set>/{agent}.yaml,\n"
        f"# selected by JAATO_PROFILE_SET.  This base MUST stay inherit-able\n"
        f"# (do not bind a provider/model here — that breaks set-selection).\n"
        f"name: _base_{agent}\n"
        f"description: {agent} stage (base; bind provider/model in a set).\n"
        f"plugins: []  # choose plugins — see `jaato-scaffold explain plugins`\n"
    )


def _set_profile_yaml(agent: str, provider: str, model: str) -> str:
    """Tier-2 set profile — binds provider+model + only valid knobs.

    Emitted knobs are gated on the provider's declared PROVIDER_KNOBS, so the
    emit step cannot author a key the validate step would reject.
    """
    info = introspect.resolve_provider(provider)
    lines = [
        f"# {agent} — {provider} set: {model}.",
        f"name: {agent}",
        f"inherits: [_base_{agent}]",
        "plugins: []  # empty keeps the inherited _base surface",
        f"model: {model}",
        f"provider: {provider}",
    ]
    knobs = info.knobs if info else None
    if knobs is not None:
        cfg = [f"plugin_configs:", f"  {provider}:"]
        if knobs.accepts("top_level", "api_key"):
            cfg.append(f"    api_key: pass://jaato/{provider}/api-key")
        if knobs.accepts("api_params", "temperature"):
            cfg.append("    api_params:")
            cfg.append("      temperature: 0.0  # determinism knob")
        if len(cfg) > 2:
            lines.extend(cfg)
    return "\n".join(lines) + "\n"


def _new_profile_set(args) -> int:
    # --- fail-loud required inputs --------------------------------------
    missing = [f for f in ("workspace", "set", "provider", "model")
               if not getattr(args, f, None)]
    if missing:
        print(f"new profile-set: missing required --{' / --'.join(missing)}")
        return 2
    if not args.agents:
        print("new profile-set: --agents a,b,c is required (the stage names)")
        return 2

    provider = args.provider
    if introspect.resolve_provider(provider) is None:
        known = ", ".join(sorted(introspect.providers()))
        print(f"new profile-set: unknown provider '{provider}' (have: {known})")
        return 2

    agents = [a.strip() for a in args.agents.split(",") if a.strip()]
    ws = Path(args.workspace).resolve()
    pdir = ws / ".jaato" / "profiles"
    setdir = pdir / args.set
    setdir.mkdir(parents=True, exist_ok=True)

    written: List[str] = []
    for agent in agents:
        base = pdir / f"_base_{agent}.yaml"
        if not base.exists() or args.force:
            base.write_text(_base_profile_yaml(agent), encoding="utf-8")
            written.append(str(base.relative_to(ws)))
        setf = setdir / f"{agent}.yaml"
        if not setf.exists() or args.force:
            setf.write_text(
                _set_profile_yaml(agent, provider, args.model), encoding="utf-8")
            written.append(str(setf.relative_to(ws)))

    # emit/merge the workspace .env so the set is SELECTED at runtime
    # (JAATO_PROFILE_SET) — without it the workspace isn't runnable as the
    # intended set.  Never clobber an existing JAATO_PROFILE_SET line.
    envf = ws / ".env"
    if not envf.exists():
        # fresh workspace — full composed .env (set selector + commented knobs)
        envf.write_text(
            _compose_env(provider, [
                "# select this profile-set at runtime (tier-2 overlay)",
                f"JAATO_PROFILE_SET={args.set}"]),
            encoding="utf-8")
        written.append(str(envf.relative_to(ws)))
    elif "JAATO_PROFILE_SET" not in envf.read_text(encoding="utf-8"):
        # existing user .env — append just the selector, don't inject template
        existing = envf.read_text(encoding="utf-8")
        prefix = existing if existing.endswith("\n") else existing + "\n"
        envf.write_text(prefix + f"JAATO_PROFILE_SET={args.set}\n",
                        encoding="utf-8")
        written.append(str(envf.relative_to(ws)))

    print(f"scaffolded profile-set '{args.set}' ({provider}/{args.model}):")
    for w in written:
        print(f"  + {w}")

    # --- emit-then-validate: the same validator the `validate` verb runs -
    print("\nre-validating scaffolded set …")
    diags = _validate.validate_workspace(str(ws), profile_set=args.set)
    errs = [d for d in diags if d.severity == "error"]
    for d in diags:
        loc = f" @ {d.where}" if d.where else ""
        print(f"  [{d.severity}] {d.profile}: {d.code}: {d.message}{loc}")
    if errs:
        print(f"\n✘ scaffold emitted {len(errs)} error(s) — this is a generator "
              "bug; please report.")
        return 1
    print("✓ scaffolded set is valid by construction.")
    return 0
